name: Nintendo Switch

on: [push, pull_request]

jobs:
  Switch-Release:
    runs-on: ubuntu-latest

    container:
      image: docker://devkitpro/devkita64
      options: --cpus 2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: catnip -T Switch

      - id: commit
        uses: prompt/actions-commit-hash@v3

      - uses: actions/upload-artifact@v4
        with:
          name: Nintendo Switch-${{ steps.commit.outputs.short }}
          path: |
            build/**/*.elf
            build/**/*.nro

  Switch-Debug:
    runs-on: ubuntu-latest

    container:
      image: docker://devkitpro/devkita64
      options: --cpus 2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: catnip -T Switch debug

      - id: commit
        uses: prompt/actions-commit-hash@v3

      - uses: actions/upload-artifact@v4
        with:
          name: Nintendo Switch (Debug)-${{ steps.commit.outputs.short }}
          path: |
            build/**/*.elf
            build/**/*.nro
