name: Nintendo 3DS

on: [push, pull_request]

jobs:
  N3DS-Release:
    runs-on: ubuntu-latest

    container:
      image: docker://devkitpro/devkitarm
      options: --cpus 2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: catnip -T 3DS

      - id: commit
        uses: prompt/actions-commit-hash@v3

      - uses: actions/upload-artifact@v4
        with:
          name: Nintendo 3DS-${{ steps.commit.outputs.short }}
          path: |
            build/**/*.elf
            build/**/*.3dsx

  N3DS-Debug:
    runs-on: ubuntu-latest

    container:
      image: docker://devkitpro/devkitarm
      options: --cpus 2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: catnip -T 3DS debug

      - id: commit
        uses: prompt/actions-commit-hash@v3

      - uses: actions/upload-artifact@v4
        with:
          name: Nintendo 3DS (Debug)-${{ steps.commit.outputs.short }}
          path: |
            build/**/*.elf
            build/**/*.3dsx
